/* Even Fibonacci Numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

function findEvenFibonacci(n) {
    // get fibo array
    let fibs = [0, 1];
    for (let i = 2; i < n; i++) {
        fibs.push( fibs[i-2] + fibs[i-1] );
    }

    // get even fibos from fibs array
    let evenFibs = [];
    for (let i=0; i<fibs.length; i++) {
        if (fibs[i] < 4000000 && fibs[i] % 2 === 0) {
            evenFibs.push(fibs[i])
        }
    }

    // sum even fibos from evenFibs array
    let sumOfEvenFibs = evenFibs.reduce((acc, curr) => {
        return acc + curr
    }, 0)

    return sumOfEvenFibs;
}

console.log( findEvenFibonacci(30) );
// Answer = 4613732